// examples/svelte/svelte-vite/src/App.svelte
<script>
  import Counter from './lib/Counter.svelte';
  import { fetchOneEntry, isPreviewing, Content } from '@builder.io/sdk-svelte';

  // Create an array of your custom components and their properties
  const CUSTOM_COMPONENTS = [
		{
			component: Counter,
			name: 'Counter',
			inputs: [
				{
					name: 'name',
					type: 'string',
					defaultValue: 'hello'
				},
				{
					name: 'count',
					type: 'number',
					defaultValue: 0
				}
			]
		},
		{
			component: SeButton,
			name: 'ContactSalesButtonFnB',
			canHaveChildren: false,
			friendlyName: 'Contact sales button',
			inputs: [
				{
					name: 'buttonText',
					type: 'text',
					defaultValue: l('Contact Sales'),
					localized: true,
					required: true,
				},
				{
					name: 'link',
					type: URL,
					localized: true,
					required: true,
				}
			]
		}
	];
  // TODO: enter your public API key
  const BUILDER_PUBLIC_API_KEY = 'f1a790f8c3204b3b8c5c1795aeac4660'; // ggignore

  let content = undefined;
  let canShowContent = false;
  const fetch = async () => {
    // fetch your Builder content
    content = await fetchOneEntry({
      model: 'page',
      apiKey: BUILDER_PUBLIC_API_KEY,
      userAttributes: {
        urlPath: window.location.pathname || '/'
      }
    });
    // handle preview mode
    canShowContent = content || isPreviewing();
  };

  fetch();
</script>

<svelte:head>
  <title>Home</title>
</svelte:head>

<main>
  <h1>
    Welcome to your new<br />Svelte app
  </h1>

  <div>Below is your Builder Content:</div>
  {#if canShowContent}
    <div>page Title: {content?.data?.title || 'Unpublished'}</div>
    <!-- Render builder content with all required props -->
    <Content
      model="page"
      {content}
      apiKey={BUILDER_PUBLIC_API_KEY}
      customComponents={CUSTOM_COMPONENTS}
    />
  {:else}
    Content Not Found
  {/if}
</main>

<footer>
  <p>visit <a href="https://svelte.dev">svelte.dev</a> to learn Svelte</p>
</footer>

<style>
  h1 {
    width: 100%;
    font-size: 2rem;
    text-align: center;
  }

  footer {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 40px;
  }

  @media (min-width: 480px) {
    footer {
      padding: 40px 0;
    }
  }
</style>

// examples/vue/nuxt-3/app.vue
<template>
  <div id="home">
    <div>Hello world from your Vue project. Below is Builder Content:</div>

    <div v-if="content || isPreviewing()">
      <div>
        page title:
        {{ content?.data?.title || 'Unpublished' }}
      </div>
      <Content
        model="page"
        :content="content"
        :api-key="BUILDER_PUBLIC_API_KEY"
        :customComponents="REGISTERED_COMPONENTS"
      />
    </div>
    <div v-else>Content not Found</div>
  </div>
</template>

<script setup>
import { Content, fetchOneEntry, isPreviewing } from '@builder.io/sdk-vue';

import HelloWorldComponent from './components/HelloWorld.vue';

// Register your Builder components
const REGISTERED_COMPONENTS = [
  {
    component: HelloWorldComponent,
    name: 'MyFunComponent',
    canHaveChildren: true,
    inputs: [
      {
        name: 'text',
        type: 'string',
        defaultValue: 'World',
      },
    ],
  },
];

// TODO: enter your public API key
// const BUILDER_PUBLIC_API_KEY = 'f1a790f8c3204b3b8c5c1795aeac4660'; // ggignore
const BUILDER_PUBLIC_API_KEY = '8f77601fe86b4125b1b1eb3b86d92d8b'

const route = useRoute();

// fetch builder content data
const { data: content } = await useAsyncData('builderData', () =>
  fetchOneEntry({
    model: 'page',
    apiKey: BUILDER_PUBLIC_API_KEY,
    userAttributes: {
      urlPath: route.path,
    },
  })
);
</script>
